name: "Build image on PR"

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          outputs: type=docker,dest=/tmp/built-docker-image.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-docker-image
          path: /tmp/built-docker-image.tar

